import type { DayPlan } from "./types";

/** Week 1–6 day-by-day curriculum derived from the timetable Phase 0–Phase 2 */
export const DAILY_PLANS: DayPlan[] = [
  // WEEK 1 — Phase 0: Engineering Foundation
  {
    week: 1, day: 1, dayOfWeek: "Monday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Linux CLI & Virtual Networking Setup",
    theory: ["What is a virtual machine?", "Virtual NICs and virtual switches", "Linux filesystem hierarchy", "Processes and services"],
    config: ["Install Ubuntu VM", "Configure static IP with ip addr", "Enable SSH", "Basic user permissions"],
    lab: "Create Ubuntu VM on virtual network. Run ip addr, ip route, ip neigh. Document every field.",
    breakFix: ["Break: wrong IP/mask", "Break: missing default route", "Fix using ip commands only"],
    recall: ["Draw VM → vSwitch → host diagram", "Explain ip addr output line by line"],
  },
  {
    week: 1, day: 2, dayOfWeek: "Tuesday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Windows Networking & Dual-VM Lab",
    theory: ["Windows TCP/IP stack", "ipconfig vs ip", "Windows firewall basics", "Name resolution on Windows"],
    config: ["Install Windows VM", "Configure IP", "Test-NetConnection", "nslookup, tracert"],
    lab: "Connect Ubuntu + Windows VMs. Ping both directions. Capture ARP and ICMP in Wireshark.",
    breakFix: ["Break: Windows firewall blocking ping", "Break: wrong subnet", "Troubleshoot layer by layer"],
    recall: ["Compare ipconfig vs ip addr output", "When does ARP happen?"],
  },
  {
    week: 1, day: 3, dayOfWeek: "Wednesday", phase: "Phase 0", module: "Engineering Foundations",
    title: "DNS, TCP Connections & Wireshark",
    theory: ["DNS resolution process", "TCP vs UDP", "Socket = IP + port", "Connection states"],
    config: ["dig, nslookup, curl on Linux", "ss -tulpn to view connections", "Configure /etc/resolv.conf"],
    lab: "Run ping, curl, dig, ssh while capturing. Identify Ethernet → ARP → IPv4 → TCP → TLS → HTTP.",
    breakFix: ["Break: wrong DNS server", "Break: host unreachable", "Use tcpdump + Wireshark to diagnose"],
    recall: ["Explain DNS query packet flow", "What is in a TCP SYN packet?"],
  },
  {
    week: 1, day: 4, dayOfWeek: "Thursday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Bash, PowerShell & Automation Basics",
    theory: ["Shell scripting purpose", "Piping and redirection", "Basic Python for networking", "Git for lab configs"],
    config: ["Write bash script: check connectivity", "PowerShell: Get-NetIPAddress", "Basic Python socket check"],
    lab: "Automate a connectivity test script that checks IP, gateway, DNS, and HTTP reachability.",
    breakFix: ["Break script when gateway changes", "Add error handling and clear output"],
    recall: ["Write connectivity check script from memory", "Explain each test's purpose"],
  },
  {
    week: 1, day: 5, dayOfWeek: "Friday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Integrated Foundation Lab",
    theory: ["Review all Phase 0 concepts", "Bridges, TAP/TUN overview", "Lab environment best practices"],
    config: ["Rebuild entire lab from scratch", "Document topology", "Snapshot VMs"],
    lab: "Full lab: 2 VMs, virtual network, Wireshark capture of ping + curl + ssh + dig. Write lab report.",
    breakFix: ["Introduce 3 different failures", "Troubleshoot using OSI bottom-up method"],
    recall: ["Draw complete lab topology from memory", "List all commands learned this week"],
  },
  {
    week: 1, day: 6, dayOfWeek: "Saturday", phase: "Phase 0", module: "Assessment",
    title: "Week 1 Assessment",
    theory: ["1 hr: explain virtual networking, DNS, TCP/IP on Linux/Windows"],
    config: ["1 hr: configure VMs, IP, DNS, SSH from scratch"],
    lab: "2 hr troubleshooting lab: 5 injected failures across both VMs",
    breakFix: ["Fix all 5 failures systematically"],
    recall: ["1 hr interview: explain ip route, ARP, DNS resolution"],
    gate: "Phase 0 exit: explain ip addr, ip route, ip neigh, ss -tulpn",
  },
  {
    week: 1, day: 7, dayOfWeek: "Sunday", phase: "Phase 0", module: "Review",
    title: "Recovery & Review",
    theory: ["Review week's mistakes", "Flashcards for commands"],
    config: [],
    lab: "Light Wireshark review — identify 5 protocols in a capture",
    breakFix: [],
    recall: ["Subnetting warm-up (10 problems)", "Draw OSI model with examples"],
  },

  // WEEK 2 — Phase 1: Network Architecture & Ethernet
  {
    week: 2, day: 1, dayOfWeek: "Monday", phase: "Phase 1", module: "Network Architecture",
    title: "OSI, TCP/IP & Encapsulation",
    theory: ["OSI 7 layers — what each actually does", "TCP/IP 4 layers", "Encapsulation/decapsulation", "PDU names at each layer", "Control/data/management planes"],
    config: ["Packet Tracer: connect 2 PCs", "Observe ARP table", "Ping and trace"],
    lab: "Build 2-PC LAN in Packet Tracer. Capture conceptually: trace ping through all layers.",
    breakFix: ["Break: wrong gateway", "Identify which layer fails"],
    recall: ["Draw encapsulation diagram without mnemonic", "Explain broadcast vs collision domain"],
  },
  {
    week: 2, day: 2, dayOfWeek: "Tuesday", phase: "Phase 1", module: "Ethernet",
    title: "Ethernet Frames & Switch Behavior",
    theory: ["Ethernet frame fields", "MAC address structure", "Unicast/broadcast/multicast", "Switch: learn, lookup, forward/flood/filter"],
    config: ["Add switch to topology", "Observe MAC table", "Generate traffic between 3 PCs"],
    lab: "Two-switch LAN. Wireshark: identify Ethernet header, MAC addresses, ARP, ICMP.",
    breakFix: ["Break: duplicate MAC", "Break: switch not learning"],
    recall: ["What happens when frame enters a switch?", "Draw switch forwarding decision tree"],
  },
  {
    week: 2, day: 3, dayOfWeek: "Wednesday", phase: "Phase 1", module: "IP Addressing",
    title: "IPv4 Binary & Subnetting Fundamentals",
    theory: ["Binary ↔ decimal", "Network/host portions", "CIDR notation", "Subnet mask", "Network/broadcast/usable range"],
    config: ["Calculate subnets by hand", "Configure IPs in different subnets", "Test connectivity"],
    lab: "Subnet 192.168.10.0/24 into 4 equal subnets. Assign and verify.",
    breakFix: ["Break: hosts in wrong subnet", "Break: wrong mask"],
    recall: ["Given 192.168.10.0/26 — network, broadcast, range", "Do 10 subnet problems timed"],
  },
  {
    week: 2, day: 4, dayOfWeek: "Thursday", phase: "Phase 1", module: "IP Addressing",
    title: "VLSM & Route Summarization",
    theory: ["VLSM design", "FLSM vs VLSM", "Route summarization", "Longest prefix match intro"],
    config: ["Design addressing for multi-department network", "Configure routers with summaries"],
    lab: "Given requirements for 4 departments with different host counts — design and implement VLSM.",
    breakFix: ["Break: overlapping subnets", "Break: summary too broad"],
    recall: ["Given 10.27.84.193/21 — all boundaries instantly", "Design VLSM from requirements"],
  },
  {
    week: 2, day: 5, dayOfWeek: "Friday", phase: "Phase 1", module: "Integrated",
    title: "Week 2 Integrated Lab",
    theory: ["Review architecture + ethernet + subnetting"],
    config: ["Multi-subnet topology with switch and router"],
    lab: "Build: 2 switches, 1 router, 3 subnets, 6 PCs. Full connectivity + Wireshark.",
    breakFix: ["Inject 4 failures across L2 and L3"],
    recall: ["Explain entire packet path PC-A to PC-B across subnets"],
  },
  {
    week: 2, day: 6, dayOfWeek: "Saturday", phase: "Phase 1", module: "Assessment",
    title: "Week 2 Assessment",
    theory: ["OSI, ethernet, subnetting written test"],
    config: ["Configure multi-subnet network from diagram"],
    lab: "2 hr troubleshooting across L2/L3",
    breakFix: ["Fix VLAN-less subnet issues, wrong masks, ARP failures"],
    recall: ["Interview: What happens when you ping across subnets?"],
  },
  {
    week: 2, day: 7, dayOfWeek: "Sunday", phase: "Phase 1", module: "Review",
    title: "Subnetting Drill Day",
    theory: [],
    config: [],
    lab: "Light packet analysis review",
    breakFix: [],
    recall: ["50 subnetting problems", "Review week's diagrams"],
  },

  // WEEK 3 — Phase 1: TCP/IP Protocols
  {
    week: 3, day: 1, dayOfWeek: "Monday", phase: "Phase 1", module: "ARP & ICMP",
    title: "ARP & ICMP Deep Dive",
    theory: ["ARP request/reply", "Gratuitous ARP", "Proxy ARP", "ICMP types", "Path MTU discovery"],
    config: ["Clear ARP cache, observe repopulation", "Ping with different sizes", "traceroute analysis"],
    lab: "Capture ARP during first ping vs second ping. Explain difference.",
    breakFix: ["Break: ARP not resolving", "Break: ICMP blocked"],
    recall: ["6 packet questions: who creates, contains, receives, inspects, changes, next"],
  },
  {
    week: 3, day: 2, dayOfWeek: "Tuesday", phase: "Phase 1", module: "TCP & UDP",
    title: "Transport Layer — TCP & UDP",
    theory: ["Three-way handshake", "TCP flags", "Sequence/ACK numbers", "Flow & congestion control", "UDP characteristics"],
    config: ["Use ss/netstat to view connections", "Capture TCP handshake in Wireshark"],
    lab: "curl, ssh, and a UDP DNS query — capture and annotate each transport header.",
    breakFix: ["Break: SYN not reaching server", "Identify with Wireshark filters"],
    recall: ["Draw TCP handshake with sequence numbers", "When is UDP preferred?"],
  },
  {
    week: 3, day: 3, dayOfWeek: "Wednesday", phase: "Phase 1", module: "DNS & DHCP",
    title: "DNS & DHCP Protocols",
    theory: ["DNS record types", "Recursive vs iterative", "DHCP DORA process", "Lease times, reservations"],
    config: ["dig +trace", "Set up DHCP server in PT", "Configure static DNS"],
    lab: "Capture full DHCP DORA and DNS query/response in Wireshark.",
    breakFix: ["Break: DHCP not assigning", "Break: DNS not resolving internal names"],
    recall: ["Explain DORA from memory", "Draw DNS resolution tree"],
  },
  {
    week: 3, day: 4, dayOfWeek: "Thursday", phase: "Phase 1", module: "IPv6",
    title: "IPv6 Fundamentals",
    theory: ["IPv6 address types", "SLAAC", "NDP vs ARP", "DHCPv6", "IPv6 routing basics"],
    config: ["Configure IPv6 addresses on Linux", "ping6, ip -6 route", "Observe NDP"],
    lab: "Dual-stack lab: IPv4 + IPv6 on same topology.",
    breakFix: ["Break: IPv6 not forwarding", "Break: NDP failure"],
    recall: ["Compare ARP vs NDP", "Identify IPv6 address type from format"],
  },
  {
    week: 3, day: 5, dayOfWeek: "Friday", phase: "Phase 1", module: "Integrated",
    title: "Protocol Stack Integration Lab",
    theory: ["Full stack review"],
    config: ["Multi-service network: DNS, DHCP, HTTP, SSH"],
    lab: "Build network where client gets IP via DHCP, resolves DNS, connects via HTTP and SSH. Capture all.",
    breakFix: ["Break each service one at a time", "Troubleshoot using packet analysis"],
    recall: ["Trace HTTP request through every layer and protocol"],
  },
  {
    week: 3, day: 6, dayOfWeek: "Saturday", phase: "Phase 1", module: "Assessment",
    title: "Week 3 Assessment",
    theory: ["Protocol theory test: ARP, ICMP, TCP, UDP, DNS, DHCP"],
    config: ["Configure DHCP + DNS server"],
    lab: "2 hr protocol troubleshooting with Wireshark",
    breakFix: ["Diagnose 5 protocol-level failures"],
    recall: ["Interview: Explain TCP vs UDP for VoIP vs file transfer"],
  },
  {
    week: 3, day: 7, dayOfWeek: "Sunday", phase: "Phase 1", module: "Review",
    title: "Packet Analysis Review",
    theory: [],
    config: [],
    lab: "Analyze 3 Wireshark captures — identify all protocols",
    breakFix: [],
    recall: ["Subnetting + protocol flashcards"],
  },

  // WEEK 4 — Phase 1 Completion & CCNA Gate Prep
  {
    week: 4, day: 1, dayOfWeek: "Monday", phase: "Phase 1", module: "Review & Gaps",
    title: "Phase 1 Gap Analysis",
    theory: ["Review all Phase 1 weak areas", "OSI, ethernet, subnetting, protocols"],
    config: ["Reconfigure any failed lab topologies"],
    lab: "Rebuild Phase 1 capstone: multi-subnet, full protocol stack",
    breakFix: ["Self-assigned break/fix on weakest topic"],
    recall: ["List top 5 concepts that aren't yet intuitive"],
  },
  {
    week: 4, day: 2, dayOfWeek: "Tuesday", phase: "Phase 1", module: "Subnetting Mastery",
    title: "Subnetting Speed Day",
    theory: ["VLSM design patterns", "Wildcard masks intro"],
    config: ["Timed subnet configuration drills"],
    lab: "Design addressing for enterprise branch with 8 departments",
    breakFix: ["Fix overlapping and wasteful allocations"],
    recall: ["50 timed subnet problems — target <30 sec each"],
  },
  {
    week: 4, day: 3, dayOfWeek: "Wednesday", phase: "Phase 1", module: "Troubleshooting",
    title: "Systematic Troubleshooting Method",
    theory: ["Bottom-up vs top-down", "Divide and conquer", "OSI-layer isolation", "Documentation"],
    config: ["Practice show/debug commands"],
    lab: "10-scenario troubleshooting lab — one failure at a time",
    breakFix: ["All 10 scenarios: document methodology used"],
    recall: ["Explain your troubleshooting framework"],
  },
  {
    week: 4, day: 4, dayOfWeek: "Thursday", phase: "Phase 1", module: "Interview Prep",
    title: "NOC/Network Analyst Interview Prep",
    theory: ["Common NOC interview topics", "Incident response basics", "Ticketing and escalation"],
    config: [],
    lab: "Mock troubleshooting scenarios under time pressure",
    breakFix: ["Simulate NOC ticket: user can't reach server"],
    recall: ["Answer 20 interview questions aloud", "Explain career path: NOC → Network Engineer"],
  },
  {
    week: 4, day: 5, dayOfWeek: "Friday", phase: "Phase 1", module: "Capstone",
    title: "Phase 1 Capstone Lab",
    theory: ["All Phase 1 concepts integrated"],
    config: ["Build from blank: switches, router, DHCP, DNS, 3 subnets"],
    lab: "Full capstone with Wireshark proof of connectivity. Write engineering report.",
    breakFix: ["Instructor injects 5 failures — fix all"],
    recall: ["Present capstone as if explaining to a junior engineer"],
  },
  {
    week: 4, day: 6, dayOfWeek: "Saturday", phase: "Phase 1", module: "Gate Assessment",
    title: "Phase 1 Gate Assessment",
    theory: ["2 hr comprehensive Phase 1 exam"],
    config: ["1 hr configuration exam from diagram"],
    lab: "2 hr troubleshooting capstone",
    breakFix: ["Fix complex multi-failure scenario"],
    recall: ["1 hr interview panel simulation"],
    gate: "Phase 1 complete → ready for Phase 2 (Switching/VLANs)",
  },
  {
    week: 4, day: 7, dayOfWeek: "Sunday", phase: "Phase 1", module: "Transition",
    title: "Phase 2 Preview & Rest",
    theory: ["Preview VLANs, 802.1Q, STP", "Read switching overview"],
    config: [],
    lab: "Light review only",
    breakFix: [],
    recall: ["Celebrate Phase 1 completion", "Set Phase 2 goals"],
  },

  // WEEK 5 — Phase 2: VLANs
  {
    week: 5, day: 1, dayOfWeek: "Monday", phase: "Phase 2", module: "VLANs",
    title: "VLAN Fundamentals & Access Ports",
    theory: ["Broadcast domain vs collision domain", "VLAN purpose: segmentation without new hardware", "Access port behavior", "Default VLAN 1", "show vlan brief interpretation"],
    config: ["vlan 10, vlan 20", "switchport mode access", "switchport access vlan <id>", "name VLANs on switch"],
    lab: "Packet Tracer: 1 switch, 4 PCs — assign VLAN 10 (Sales) and VLAN 20 (Engineering). Verify same-VLAN ping works, cross-VLAN fails.",
    breakFix: ["Break: PC on wrong access VLAN", "Break: port left in VLAN 1", "Fix with show vlan brief + switchport commands"],
    recall: ["Why can't VLAN 10 ping VLAN 20 without a router?", "Draw switch with two VLANs and label broadcast domains"],
  },
  {
    week: 5, day: 2, dayOfWeek: "Tuesday", phase: "Phase 2", module: "VLANs",
    title: "802.1Q Trunking & Native VLAN",
    theory: ["Trunk carries multiple VLANs", "802.1Q tag fields (TPID, PCP, VID)", "Tagged vs untagged frames", "Native VLAN mismatch risk", "DTP overview (auto/desirable/nonegotiate)"],
    config: ["switchport trunk encapsulation dot1q", "switchport mode trunk", "switchport trunk allowed vlan", "switchport trunk native vlan"],
    lab: "Two-switch topology: PCs on VLAN 10 and 20 across switches. Configure dot1Q trunk. Capture/verify with show interfaces trunk.",
    breakFix: ["Break: trunk set to access on one side", "Break: native VLAN mismatch", "Break: allowed VLAN list missing VLAN 20"],
    recall: ["What happens to untagged traffic on a trunk?", "Explain native VLAN mismatch symptom"],
  },
  {
    week: 5, day: 3, dayOfWeek: "Wednesday", phase: "Phase 2", module: "VLANs",
    title: "Inter-VLAN Routing with SVIs",
    theory: ["L3 switch as default gateway per VLAN", "SVI = VLAN interface with IP", "Routing between VLANs on same switch", "ip routing on multilayer switch", "Connected/directly connected routes"],
    config: ["interface vlan 10 / ip address", "interface vlan 20 / ip address", "ip routing", "PC default gateways → SVI IPs"],
    lab: "Multilayer switch: VLAN 10 (192.168.10.0/24) and VLAN 20 (192.168.20.0/24). Configure SVIs. Full inter-VLAN connectivity.",
    breakFix: ["Break: SVI shut down", "Break: wrong SVI IP/mask", "Break: ip routing disabled", "Break: PC gateway wrong"],
    recall: ["Draw inter-VLAN flow: PC-A → SVI → PC-B", "Difference between SVI and subinterface?"],
  },
  {
    week: 5, day: 4, dayOfWeek: "Thursday", phase: "Phase 2", module: "VLANs",
    title: "Router-on-a-Stick (ROAS)",
    theory: ["When to use external router vs L3 switch", "Subinterfaces and 802.1Q encapsulation", "One physical link, multiple VLAN gateways", "ROAS scaling limits", "Trunk from router to switch"],
    config: ["interface g0/0.10 encapsulation dot1Q 10", "interface g0/0.20 encapsulation dot1Q 20", "ip address on each subinterface", "Trunk to router port"],
    lab: "L2 switch + router: VLAN 10 & 20 with ROAS. Remove L3 switch from yesterday's lab — achieve same connectivity with router subinterfaces.",
    breakFix: ["Break: missing encapsulation dot1Q", "Break: native VLAN on trunk conflicts with subinterface", "Break: subinterface admin down"],
    recall: ["Compare ROAS vs SVI — when use each?", "Write ROAS config from memory"],
  },
  {
    week: 5, day: 5, dayOfWeek: "Friday", phase: "Phase 2", module: "VLANs",
    title: "Integrated VLAN Lab",
    theory: ["VLAN design best practices", "Management VLAN separation", "Voice VLAN intro", "Documenting VLAN scheme"],
    config: ["Multi-switch VLAN design", "Access + trunk + SVI or ROAS combined", "show vlan, show interfaces trunk, show ip route"],
    lab: "EVE-NG/PT: 2 switches, 1 router or L3 switch, 3 VLANs (10/20/99 mgmt), 6 PCs. Full connectivity + management VLAN. Write VLAN table.",
    breakFix: ["Inject VLAN mismatch, trunk down, missing SVI, wrong gateway — fix all 4"],
    recall: ["Present VLAN design as engineering doc", "List every show command for VLAN troubleshooting"],
  },
  {
    week: 5, day: 6, dayOfWeek: "Saturday", phase: "Phase 2", module: "Assessment",
    title: "Week 5 VLAN Assessment",
    theory: ["1 hr: access vs trunk, 802.1Q, native VLAN, inter-VLAN routing theory"],
    config: ["1 hr: build VLAN topology from diagram — access, trunk, SVI or ROAS"],
    lab: "2 hr VLAN troubleshooting: 5 injected failures (mismatch, native VLAN, missing route, wrong gateway, trunk allowed list)",
    breakFix: ["Fix all 5 failures using show vlan, show interfaces trunk, show ip route"],
    recall: ["1 hr interview: explain inter-VLAN routing paths", "Draw ROAS and SVI topologies from memory"],
    gate: "VLAN competency: configure access/trunk, inter-VLAN routing via SVI or ROAS",
  },
  {
    week: 5, day: 7, dayOfWeek: "Sunday", phase: "Phase 2", module: "Review",
    title: "Recovery & Review",
    theory: ["Review VLAN week mistakes", "Flashcards: 802.1Q, native VLAN, SVI"],
    config: [],
    lab: "Light Packet Tracer review — rebuild mini VLAN lab in 20 min",
    breakFix: [],
    recall: ["Subnetting warm-up (10 problems)", "Preview STP — why do switches need loop prevention?"],
  },

  // WEEK 6 — Phase 2: STP & Layer-2 Resiliency
  {
    week: 6, day: 1, dayOfWeek: "Monday", phase: "Phase 2", module: "STP",
    title: "STP Fundamentals & Loop Danger",
    theory: ["Broadcast storm mechanism", "MAC table instability", "Duplicate frames", "STP purpose: logical loop-free topology", "802.1D overview: BPDUs block redundant paths"],
    config: ["Observe default STP on switches", "show spanning-tree", "show spanning-tree vlan <id>"],
    lab: "Packet Tracer: triangle topology (3 switches, 3 links). Before STP converges, observe blocked port. Document root bridge election.",
    breakFix: ["Break: disable STP on one switch (if lab allows) — observe storm symptoms", "Re-enable and verify convergence"],
    recall: ["What three problems does a L2 loop cause?", "Why is STP required in redundant topologies?"],
  },
  {
    week: 6, day: 2, dayOfWeek: "Tuesday", phase: "Phase 2", module: "STP",
    title: "Root Bridge, Port Roles & States",
    theory: ["Root bridge election (lowest bridge ID)", "Bridge ID = priority + MAC", "Port roles: Root, Designated, Alternate/Blocked", "Port states: Blocking, Listening, Learning, Forwarding", "spanning-tree vlan <id> root primary/secondary"],
    config: ["spanning-tree vlan 1 root primary", "spanning-tree vlan 1 priority 4096", "show spanning-tree detail"],
    lab: "Same triangle topology: manually set root bridge on SW1. Verify which ports become Root/Designated/Alternate on each switch.",
    breakFix: ["Break: unexpected root bridge — wrong priority", "Break: suboptimal blocked port — fix root placement"],
    recall: ["Draw triangle with port roles labeled", "How is root bridge elected step by step?"],
  },
  {
    week: 6, day: 3, dayOfWeek: "Wednesday", phase: "Phase 2", module: "STP",
    title: "RSTP & BPDU Deep Dive",
    theory: ["802.1w RSTP improvements", "RSTP port roles: Alternate, Backup", "Proposal/agreement sync", "BPDU fields and hello timer", "PVST+ vs RSTP vs MST overview"],
    config: ["spanning-tree mode rapid-pvst", "spanning-tree portfast (preview)", "debug spanning-tree events (lab only)"],
    lab: "Convert triangle lab to rapid-PVST. Unplug active link — measure reconvergence. Compare to classic STP timing.",
    breakFix: ["Break: mixed STP modes between switches", "Break: BPDU not received — port stays forwarding"],
    recall: ["RSTP vs STP convergence difference", "What does a BPDU contain?"],
  },
  {
    week: 6, day: 4, dayOfWeek: "Thursday", phase: "Phase 2", module: "STP",
    title: "PortFast, BPDU Guard & Edge Ports",
    theory: ["PortFast: skip listening/learning on access ports", "BPDU Guard: shut port if BPDU received", "Where PortFast is safe (end hosts only)", "Root Guard and Loop Guard intro", "spanning-tree bpduguard enable"],
    config: ["spanning-tree portfast", "spanning-tree bpduguard enable", "spanning-tree guard root (on trunk ports)"],
    lab: "Access port with PC: enable PortFast — verify immediate forwarding. Connect switch to PortFast port — observe BPDU Guard err-disable.",
    breakFix: ["Break: PortFast on trunk — diagnose risk", "Break: err-disabled port from BPDU Guard — recover with shut/no shut after fix"],
    recall: ["When must you NOT use PortFast?", "Explain BPDU Guard purpose in one sentence"],
  },
  {
    week: 6, day: 5, dayOfWeek: "Friday", phase: "Phase 2", module: "STP",
    title: "EtherChannel & LACP",
    theory: ["EtherChannel benefits: bandwidth + redundancy", "PAgP vs LACP (802.3ad)", "LACP active/passive modes", "EtherChannel constraints: speed, duplex, VLAN, STP treated as one link", "Load balancing across member links"],
    config: ["interface range g0/1-2", "channel-group 1 mode active", "interface port-channel 1", "show etherchannel summary"],
    lab: "Two switches with dual links: configure LACP EtherChannel. Verify STP sees one logical link. Fail one member — traffic continues.",
    breakFix: ["Break: mode mismatch (active on one side, on other)", "Break: inconsistent VLAN/trunk on member port", "Break: channel not forming — mismatched speed"],
    recall: ["Draw before/after STP with EtherChannel", "LACP active vs passive — when to use each?"],
  },
  {
    week: 6, day: 6, dayOfWeek: "Saturday", phase: "Phase 2", module: "Assessment",
    title: "Week 6 STP Assessment",
    theory: ["1 hr: STP/RSTP theory, port roles, BPDU, PortFast, EtherChannel"],
    config: ["1 hr: triangle topology — set root, enable RSTP, configure PortFast on access ports"],
    lab: "2 hr STP troubleshooting: 5 failures (wrong root, loop from disabled STP, BPDU Guard err-disable, EtherChannel mismatch, blocked port)",
    breakFix: ["Fix all 5 using show spanning-tree, show etherchannel summary, show interfaces status err-disabled"],
    recall: ["1 hr interview: explain STP convergence after link failure", "Design redundant L2 topology that is loop-safe"],
    gate: "STP competency: predict blocked ports, configure RSTP, PortFast/BPDU Guard, LACP EtherChannel",
  },
  {
    week: 6, day: 7, dayOfWeek: "Sunday", phase: "Phase 2", module: "Review",
    title: "Recovery & Review",
    theory: ["Review STP week mistakes", "Flashcards: port roles, BPDU, EtherChannel"],
    config: [],
    lab: "Light review — draw triangle topology with STP port states from memory",
    breakFix: [],
    recall: ["Subnetting warm-up (10 problems)", "Preview Phase 3 routing — static routes and OSPF"],
  },
];

export function getDayPlan(week: number, day: number): DayPlan | undefined {
  return DAILY_PLANS.find((p) => p.week === week && p.day === day);
}

export function getWeekPlans(week: number): DayPlan[] {
  return DAILY_PLANS.filter((p) => p.week === week);
}

export function dayKey(week: number, day: number): string {
  return `w${week}-d${day}`;
}
