import type { DayPlan } from "./types";

/** Week 1–4 day-by-day curriculum derived from the timetable Phase 0 & Phase 1 */
export const DAILY_PLANS: DayPlan[] = [
  // WEEK 1 — Phase 0: Engineering Foundation
  {
    week: 1, day: 1, dayOfWeek: "Monday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Linux CLI & Virtual Networking Setup",
    theory: ["What is a virtual machine?", "Virtual NICs and virtual switches", "Linux filesystem hierarchy", "Processes and services"],
    config: ["Install Ubuntu VM", "Configure static IP with ip addr", "Enable SSH", "Basic user permissions"],
    lab: "Create Ubuntu VM on virtual network. Run ip addr, ip route, ip neigh. Document every field.",
    breakFix: ["Break: wrong IP/mask", "Break: missing default route", "Fix using ip commands only"],
    recall: ["Draw VM → vSwitch → host diagram", "Explain ip addr output line by line"],
  },
  {
    week: 1, day: 2, dayOfWeek: "Tuesday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Windows Networking & Dual-VM Lab",
    theory: ["Windows TCP/IP stack", "ipconfig vs ip", "Windows firewall basics", "Name resolution on Windows"],
    config: ["Install Windows VM", "Configure IP", "Test-NetConnection", "nslookup, tracert"],
    lab: "Connect Ubuntu + Windows VMs. Ping both directions. Capture ARP and ICMP in Wireshark.",
    breakFix: ["Break: Windows firewall blocking ping", "Break: wrong subnet", "Troubleshoot layer by layer"],
    recall: ["Compare ipconfig vs ip addr output", "When does ARP happen?"],
  },
  {
    week: 1, day: 3, dayOfWeek: "Wednesday", phase: "Phase 0", module: "Engineering Foundations",
    title: "DNS, TCP Connections & Wireshark",
    theory: ["DNS resolution process", "TCP vs UDP", "Socket = IP + port", "Connection states"],
    config: ["dig, nslookup, curl on Linux", "ss -tulpn to view connections", "Configure /etc/resolv.conf"],
    lab: "Run ping, curl, dig, ssh while capturing. Identify Ethernet → ARP → IPv4 → TCP → TLS → HTTP.",
    breakFix: ["Break: wrong DNS server", "Break: host unreachable", "Use tcpdump + Wireshark to diagnose"],
    recall: ["Explain DNS query packet flow", "What is in a TCP SYN packet?"],
  },
  {
    week: 1, day: 4, dayOfWeek: "Thursday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Bash, PowerShell & Automation Basics",
    theory: ["Shell scripting purpose", "Piping and redirection", "Basic Python for networking", "Git for lab configs"],
    config: ["Write bash script: check connectivity", "PowerShell: Get-NetIPAddress", "Basic Python socket check"],
    lab: "Automate a connectivity test script that checks IP, gateway, DNS, and HTTP reachability.",
    breakFix: ["Break script when gateway changes", "Add error handling and clear output"],
    recall: ["Write connectivity check script from memory", "Explain each test's purpose"],
  },
  {
    week: 1, day: 5, dayOfWeek: "Friday", phase: "Phase 0", module: "Engineering Foundations",
    title: "Integrated Foundation Lab",
    theory: ["Review all Phase 0 concepts", "Bridges, TAP/TUN overview", "Lab environment best practices"],
    config: ["Rebuild entire lab from scratch", "Document topology", "Snapshot VMs"],
    lab: "Full lab: 2 VMs, virtual network, Wireshark capture of ping + curl + ssh + dig. Write lab report.",
    breakFix: ["Introduce 3 different failures", "Troubleshoot using OSI bottom-up method"],
    recall: ["Draw complete lab topology from memory", "List all commands learned this week"],
  },
  {
    week: 1, day: 6, dayOfWeek: "Saturday", phase: "Phase 0", module: "Assessment",
    title: "Week 1 Assessment",
    theory: ["1 hr: explain virtual networking, DNS, TCP/IP on Linux/Windows"],
    config: ["1 hr: configure VMs, IP, DNS, SSH from scratch"],
    lab: "2 hr troubleshooting lab: 5 injected failures across both VMs",
    breakFix: ["Fix all 5 failures systematically"],
    recall: ["1 hr interview: explain ip route, ARP, DNS resolution"],
    gate: "Phase 0 exit: explain ip addr, ip route, ip neigh, ss -tulpn",
  },
  {
    week: 1, day: 7, dayOfWeek: "Sunday", phase: "Phase 0", module: "Review",
    title: "Recovery & Review",
    theory: ["Review week's mistakes", "Flashcards for commands"],
    config: [],
    lab: "Light Wireshark review — identify 5 protocols in a capture",
    breakFix: [],
    recall: ["Subnetting warm-up (10 problems)", "Draw OSI model with examples"],
  },

  // WEEK 2 — Phase 1: Network Architecture & Ethernet
  {
    week: 2, day: 1, dayOfWeek: "Monday", phase: "Phase 1", module: "Network Architecture",
    title: "OSI, TCP/IP & Encapsulation",
    theory: ["OSI 7 layers — what each actually does", "TCP/IP 4 layers", "Encapsulation/decapsulation", "PDU names at each layer", "Control/data/management planes"],
    config: ["Packet Tracer: connect 2 PCs", "Observe ARP table", "Ping and trace"],
    lab: "Build 2-PC LAN in Packet Tracer. Capture conceptually: trace ping through all layers.",
    breakFix: ["Break: wrong gateway", "Identify which layer fails"],
    recall: ["Draw encapsulation diagram without mnemonic", "Explain broadcast vs collision domain"],
  },
  {
    week: 2, day: 2, dayOfWeek: "Tuesday", phase: "Phase 1", module: "Ethernet",
    title: "Ethernet Frames & Switch Behavior",
    theory: ["Ethernet frame fields", "MAC address structure", "Unicast/broadcast/multicast", "Switch: learn, lookup, forward/flood/filter"],
    config: ["Add switch to topology", "Observe MAC table", "Generate traffic between 3 PCs"],
    lab: "Two-switch LAN. Wireshark: identify Ethernet header, MAC addresses, ARP, ICMP.",
    breakFix: ["Break: duplicate MAC", "Break: switch not learning"],
    recall: ["What happens when frame enters a switch?", "Draw switch forwarding decision tree"],
  },
  {
    week: 2, day: 3, dayOfWeek: "Wednesday", phase: "Phase 1", module: "IP Addressing",
    title: "IPv4 Binary & Subnetting Fundamentals",
    theory: ["Binary ↔ decimal", "Network/host portions", "CIDR notation", "Subnet mask", "Network/broadcast/usable range"],
    config: ["Calculate subnets by hand", "Configure IPs in different subnets", "Test connectivity"],
    lab: "Subnet 192.168.10.0/24 into 4 equal subnets. Assign and verify.",
    breakFix: ["Break: hosts in wrong subnet", "Break: wrong mask"],
    recall: ["Given 192.168.10.0/26 — network, broadcast, range", "Do 10 subnet problems timed"],
  },
  {
    week: 2, day: 4, dayOfWeek: "Thursday", phase: "Phase 1", module: "IP Addressing",
    title: "VLSM & Route Summarization",
    theory: ["VLSM design", "FLSM vs VLSM", "Route summarization", "Longest prefix match intro"],
    config: ["Design addressing for multi-department network", "Configure routers with summaries"],
    lab: "Given requirements for 4 departments with different host counts — design and implement VLSM.",
    breakFix: ["Break: overlapping subnets", "Break: summary too broad"],
    recall: ["Given 10.27.84.193/21 — all boundaries instantly", "Design VLSM from requirements"],
  },
  {
    week: 2, day: 5, dayOfWeek: "Friday", phase: "Phase 1", module: "Integrated",
    title: "Week 2 Integrated Lab",
    theory: ["Review architecture + ethernet + subnetting"],
    config: ["Multi-subnet topology with switch and router"],
    lab: "Build: 2 switches, 1 router, 3 subnets, 6 PCs. Full connectivity + Wireshark.",
    breakFix: ["Inject 4 failures across L2 and L3"],
    recall: ["Explain entire packet path PC-A to PC-B across subnets"],
  },
  {
    week: 2, day: 6, dayOfWeek: "Saturday", phase: "Phase 1", module: "Assessment",
    title: "Week 2 Assessment",
    theory: ["OSI, ethernet, subnetting written test"],
    config: ["Configure multi-subnet network from diagram"],
    lab: "2 hr troubleshooting across L2/L3",
    breakFix: ["Fix VLAN-less subnet issues, wrong masks, ARP failures"],
    recall: ["Interview: What happens when you ping across subnets?"],
  },
  {
    week: 2, day: 7, dayOfWeek: "Sunday", phase: "Phase 1", module: "Review",
    title: "Subnetting Drill Day",
    theory: [],
    config: [],
    lab: "Light packet analysis review",
    breakFix: [],
    recall: ["50 subnetting problems", "Review week's diagrams"],
  },

  // WEEK 3 — Phase 1: TCP/IP Protocols
  {
    week: 3, day: 1, dayOfWeek: "Monday", phase: "Phase 1", module: "ARP & ICMP",
    title: "ARP & ICMP Deep Dive",
    theory: ["ARP request/reply", "Gratuitous ARP", "Proxy ARP", "ICMP types", "Path MTU discovery"],
    config: ["Clear ARP cache, observe repopulation", "Ping with different sizes", "traceroute analysis"],
    lab: "Capture ARP during first ping vs second ping. Explain difference.",
    breakFix: ["Break: ARP not resolving", "Break: ICMP blocked"],
    recall: ["6 packet questions: who creates, contains, receives, inspects, changes, next"],
  },
  {
    week: 3, day: 2, dayOfWeek: "Tuesday", phase: "Phase 1", module: "TCP & UDP",
    title: "Transport Layer — TCP & UDP",
    theory: ["Three-way handshake", "TCP flags", "Sequence/ACK numbers", "Flow & congestion control", "UDP characteristics"],
    config: ["Use ss/netstat to view connections", "Capture TCP handshake in Wireshark"],
    lab: "curl, ssh, and a UDP DNS query — capture and annotate each transport header.",
    breakFix: ["Break: SYN not reaching server", "Identify with Wireshark filters"],
    recall: ["Draw TCP handshake with sequence numbers", "When is UDP preferred?"],
  },
  {
    week: 3, day: 3, dayOfWeek: "Wednesday", phase: "Phase 1", module: "DNS & DHCP",
    title: "DNS & DHCP Protocols",
    theory: ["DNS record types", "Recursive vs iterative", "DHCP DORA process", "Lease times, reservations"],
    config: ["dig +trace", "Set up DHCP server in PT", "Configure static DNS"],
    lab: "Capture full DHCP DORA and DNS query/response in Wireshark.",
    breakFix: ["Break: DHCP not assigning", "Break: DNS not resolving internal names"],
    recall: ["Explain DORA from memory", "Draw DNS resolution tree"],
  },
  {
    week: 3, day: 4, dayOfWeek: "Thursday", phase: "Phase 1", module: "IPv6",
    title: "IPv6 Fundamentals",
    theory: ["IPv6 address types", "SLAAC", "NDP vs ARP", "DHCPv6", "IPv6 routing basics"],
    config: ["Configure IPv6 addresses on Linux", "ping6, ip -6 route", "Observe NDP"],
    lab: "Dual-stack lab: IPv4 + IPv6 on same topology.",
    breakFix: ["Break: IPv6 not forwarding", "Break: NDP failure"],
    recall: ["Compare ARP vs NDP", "Identify IPv6 address type from format"],
  },
  {
    week: 3, day: 5, dayOfWeek: "Friday", phase: "Phase 1", module: "Integrated",
    title: "Protocol Stack Integration Lab",
    theory: ["Full stack review"],
    config: ["Multi-service network: DNS, DHCP, HTTP, SSH"],
    lab: "Build network where client gets IP via DHCP, resolves DNS, connects via HTTP and SSH. Capture all.",
    breakFix: ["Break each service one at a time", "Troubleshoot using packet analysis"],
    recall: ["Trace HTTP request through every layer and protocol"],
  },
  {
    week: 3, day: 6, dayOfWeek: "Saturday", phase: "Phase 1", module: "Assessment",
    title: "Week 3 Assessment",
    theory: ["Protocol theory test: ARP, ICMP, TCP, UDP, DNS, DHCP"],
    config: ["Configure DHCP + DNS server"],
    lab: "2 hr protocol troubleshooting with Wireshark",
    breakFix: ["Diagnose 5 protocol-level failures"],
    recall: ["Interview: Explain TCP vs UDP for VoIP vs file transfer"],
  },
  {
    week: 3, day: 7, dayOfWeek: "Sunday", phase: "Phase 1", module: "Review",
    title: "Packet Analysis Review",
    theory: [],
    config: [],
    lab: "Analyze 3 Wireshark captures — identify all protocols",
    breakFix: [],
    recall: ["Subnetting + protocol flashcards"],
  },

  // WEEK 4 — Phase 1 Completion & CCNA Gate Prep
  {
    week: 4, day: 1, dayOfWeek: "Monday", phase: "Phase 1", module: "Review & Gaps",
    title: "Phase 1 Gap Analysis",
    theory: ["Review all Phase 1 weak areas", "OSI, ethernet, subnetting, protocols"],
    config: ["Reconfigure any failed lab topologies"],
    lab: "Rebuild Phase 1 capstone: multi-subnet, full protocol stack",
    breakFix: ["Self-assigned break/fix on weakest topic"],
    recall: ["List top 5 concepts that aren't yet intuitive"],
  },
  {
    week: 4, day: 2, dayOfWeek: "Tuesday", phase: "Phase 1", module: "Subnetting Mastery",
    title: "Subnetting Speed Day",
    theory: ["VLSM design patterns", "Wildcard masks intro"],
    config: ["Timed subnet configuration drills"],
    lab: "Design addressing for enterprise branch with 8 departments",
    breakFix: ["Fix overlapping and wasteful allocations"],
    recall: ["50 timed subnet problems — target <30 sec each"],
  },
  {
    week: 4, day: 3, dayOfWeek: "Wednesday", phase: "Phase 1", module: "Troubleshooting",
    title: "Systematic Troubleshooting Method",
    theory: ["Bottom-up vs top-down", "Divide and conquer", "OSI-layer isolation", "Documentation"],
    config: ["Practice show/debug commands"],
    lab: "10-scenario troubleshooting lab — one failure at a time",
    breakFix: ["All 10 scenarios: document methodology used"],
    recall: ["Explain your troubleshooting framework"],
  },
  {
    week: 4, day: 4, dayOfWeek: "Thursday", phase: "Phase 1", module: "Interview Prep",
    title: "NOC/Network Analyst Interview Prep",
    theory: ["Common NOC interview topics", "Incident response basics", "Ticketing and escalation"],
    config: [],
    lab: "Mock troubleshooting scenarios under time pressure",
    breakFix: ["Simulate NOC ticket: user can't reach server"],
    recall: ["Answer 20 interview questions aloud", "Explain career path: NOC → Network Engineer"],
  },
  {
    week: 4, day: 5, dayOfWeek: "Friday", phase: "Phase 1", module: "Capstone",
    title: "Phase 1 Capstone Lab",
    theory: ["All Phase 1 concepts integrated"],
    config: ["Build from blank: switches, router, DHCP, DNS, 3 subnets"],
    lab: "Full capstone with Wireshark proof of connectivity. Write engineering report.",
    breakFix: ["Instructor injects 5 failures — fix all"],
    recall: ["Present capstone as if explaining to a junior engineer"],
  },
  {
    week: 4, day: 6, dayOfWeek: "Saturday", phase: "Phase 1", module: "Gate Assessment",
    title: "Phase 1 Gate Assessment",
    theory: ["2 hr comprehensive Phase 1 exam"],
    config: ["1 hr configuration exam from diagram"],
    lab: "2 hr troubleshooting capstone",
    breakFix: ["Fix complex multi-failure scenario"],
    recall: ["1 hr interview panel simulation"],
    gate: "Phase 1 complete → ready for Phase 2 (Switching/VLANs)",
  },
  {
    week: 4, day: 7, dayOfWeek: "Sunday", phase: "Phase 1", module: "Transition",
    title: "Phase 2 Preview & Rest",
    theory: ["Preview VLANs, 802.1Q, STP", "Read switching overview"],
    config: [],
    lab: "Light review only",
    breakFix: [],
    recall: ["Celebrate Phase 1 completion", "Set Phase 2 goals"],
  },
];

export function getDayPlan(week: number, day: number): DayPlan | undefined {
  return DAILY_PLANS.find((p) => p.week === week && p.day === day);
}

export function getWeekPlans(week: number): DayPlan[] {
  return DAILY_PLANS.filter((p) => p.week === week);
}

export function dayKey(week: number, day: number): string {
  return `w${week}-d${day}`;
}
