import type { Resource, ResourceType } from "./types";

export const RESOURCE_TYPES: { id: ResourceType; label: string }[] = [
  { id: "documentation", label: "Documentation" },
  { id: "book", label: "Books" },
  { id: "video", label: "Video Courses" },
  { id: "lab", label: "Labs & Practice" },
  { id: "cert-prep", label: "Cert Prep" },
  { id: "tool", label: "Tools" },
  { id: "community", label: "Communities" },
];

export const RESOURCES: Resource[] = [
  // Documentation
  {
    id: "rfc-791",
    title: "RFC 791 — Internet Protocol",
    url: "https://datatracker.ietf.org/doc/html/rfc791",
    type: "documentation",
    description: "The IPv4 specification — foundational reading for Phase 1.",
    phases: ["phase-1"],
    tags: ["IPv4", "RFC", "fundamentals"],
    free: true,
  },
  {
    id: "rfc-826",
    title: "RFC 826 — ARP",
    url: "https://datatracker.ietf.org/doc/html/rfc826",
    type: "documentation",
    description: "Address Resolution Protocol — understand L2/L3 binding.",
    phases: ["phase-1"],
    tags: ["ARP", "RFC", "L2"],
    free: true,
  },
  {
    id: "rfc-2328",
    title: "RFC 2328 — OSPF v2",
    url: "https://datatracker.ietf.org/doc/html/rfc2328",
    type: "documentation",
    description: "OSPF protocol specification for Phase 2 routing depth.",
    phases: ["phase-2"],
    tags: ["OSPF", "routing", "RFC"],
    free: true,
  },
  {
    id: "cisco-doc",
    title: "Cisco IOS Command Reference",
    url: "https://www.cisco.com/c/en/us/support/ios-nx-os-software/ios-15-4m-t/products-command-reference-list.html",
    type: "documentation",
    description: "Official Cisco CLI reference for configuration blocks.",
    tags: ["Cisco", "CLI", "configuration"],
    free: true,
  },
  {
    id: "wireshark-docs",
    title: "Wireshark User Guide",
    url: "https://www.wireshark.org/docs/wsug_html_chunked/",
    type: "documentation",
    description: "Packet capture analysis — essential for every lab.",
    tags: ["Wireshark", "packet analysis", "troubleshooting"],
    free: true,
  },
  {
    id: "azure-network-docs",
    title: "Microsoft Learn — Azure Networking",
    url: "https://learn.microsoft.com/en-us/azure/networking/",
    type: "documentation",
    description: "VNet, NSG, UDR, VPN Gateway, ExpressRoute documentation.",
    phases: ["phase-5", "phase-6"],
    tags: ["Azure", "cloud", "VNet"],
    free: true,
  },
  {
    id: "fortinet-docs",
    title: "FortiGate Administration Guide",
    url: "https://docs.fortinet.com/product/fortigate",
    type: "documentation",
    description: "FortiOS firewall, VPN, and security policy reference.",
    phases: ["phase-4"],
    tags: ["FortiGate", "firewall", "VPN"],
    free: true,
  },

  // Books
  {
    id: "book-ocg-ccna",
    title: "CCNA 200-301 Official Cert Guide (Odom)",
    url: "https://www.ciscopress.com/store/ccna-200-301-official-cert-guide-volume-1-9780135792735",
    type: "book",
    description: "Primary CCNA study text — read alongside Phase 1–3 modules.",
    phases: ["phase-1", "phase-2", "phase-3"],
    tags: ["CCNA", "Cisco", "certification"],
  },
  {
    id: "book-tcp-ip",
    title: "TCP/IP Illustrated, Vol. 1 (Stevens)",
    url: "https://www.pearson.com/en-us/subject-catalog/p/tcp-ip-illustrated-volume-1/P200000003380",
    type: "book",
    description: "Deep protocol behavior with packet-level detail.",
    phases: ["phase-1"],
    tags: ["TCP/IP", "protocols", "deep-dive"],
  },
  {
    id: "book-routing-tcp",
    title: "Routing TCP/IP, Vol. 1 (Doyle & Carroll)",
    url: "https://www.ciscopress.com/store/routing-tcp-ip-volume-i-2nd-edition-9781587052026",
    type: "book",
    description: "IGP mastery — OSPF, EIGRP internals for Phase 2–3.",
    phases: ["phase-2", "phase-3"],
    tags: ["routing", "OSPF", "EIGRP"],
  },
  {
    id: "book-network-warrior",
    title: "Network Warrior (Donahue)",
    url: "https://www.oreilly.com/library/view/network-warrior/9781449391938/",
    type: "book",
    description: "Real-world NOC/engineer perspective — practical troubleshooting.",
    tags: ["troubleshooting", "NOC", "practical"],
  },
  {
    id: "book-unix-network",
    title: "UNIX Network Programming (Stevens)",
    url: "https://www.pearson.com/en-us/subject-catalog/p/unix-network-programming-volume-1/P200000003382",
    type: "book",
    description: "Socket programming and network stack from the OS perspective.",
    phases: ["phase-0"],
    tags: ["Linux", "sockets", "programming"],
  },

  // Video Courses
  {
    id: "video-jeremy-ccna",
    title: "Jeremy's IT Lab — Free CCNA",
    url: "https://www.jeremysitlab.com/",
    type: "video",
    description: "Free CCNA course with labs — use for theory reinforcement only.",
    phases: ["phase-1", "phase-2"],
    tags: ["CCNA", "free", "video"],
    free: true,
  },
  {
    id: "video-networkchuck",
    title: "NetworkChuck — YouTube",
    url: "https://www.youtube.com/@NetworkChuck",
    type: "video",
    description: "Motivation and concept overviews — not a replacement for labs.",
    tags: ["motivation", "overview", "free"],
    free: true,
  },
  {
    id: "video-david-bombal",
    title: "David Bombal — CCNA/CCNP Labs",
    url: "https://www.youtube.com/@davidbombal",
    type: "video",
    description: "Hands-on lab walkthroughs for Packet Tracer and GNS3.",
    phases: ["phase-1", "phase-2"],
    tags: ["labs", "Cisco", "hands-on"],
    free: true,
  },
  {
    id: "video-flackbox",
    title: "Flackbox — Azure Networking",
    url: "https://www.youtube.com/@Flackbox",
    type: "video",
    description: "Azure networking deep dives for AZ-700 preparation.",
    phases: ["phase-5", "phase-6"],
    tags: ["Azure", "cloud", "AZ-700"],
    free: true,
  },
  {
    id: "video-keith-barker",
    title: "CBT Nuggets — Keith Barker",
    url: "https://www.cbtnuggets.com/trainers/keith-barker",
    type: "video",
    description: "Concise cert-focused training for CCNA through CCNP.",
    tags: ["certification", "Cisco", "structured"],
  },

  // Labs & Practice
  {
    id: "lab-packet-tracer",
    title: "Cisco Packet Tracer",
    url: "https://www.netacad.com/cisco-packet-tracer",
    type: "lab",
    description: "Free network simulation — primary tool for Phases 1–3.",
    phases: ["phase-1", "phase-2", "phase-3"],
    tags: ["simulation", "Cisco", "free"],
    free: true,
  },
  {
    id: "lab-eveng",
    title: "EVE-NG Community Edition",
    url: "https://www.eve-ng.net/",
    type: "lab",
    description: "Advanced multi-vendor emulation for Phase 3+ topologies.",
    phases: ["phase-2", "phase-3", "phase-4"],
    tags: ["emulation", "multi-vendor", "advanced"],
    free: true,
  },
  {
    id: "lab-gns3",
    title: "GNS3",
    url: "https://www.gns3.com/",
    type: "lab",
    description: "Network emulation with real IOS images.",
    phases: ["phase-2", "phase-3"],
    tags: ["emulation", "Cisco", "real-images"],
    free: true,
  },
  {
    id: "lab-boson-netsim",
    title: "Boson NetSim",
    url: "https://www.boson.com/netsim",
    type: "lab",
    description: "CCNA/CCNP lab simulator with structured scenarios.",
    tags: ["CCNA", "simulation", "structured"],
  },
  {
    id: "lab-azure-free",
    title: "Azure Free Account",
    url: "https://azure.microsoft.com/en-us/free/",
    type: "lab",
    description: "$200 credit for VNet, VPN, and NSG hands-on labs.",
    phases: ["phase-5", "phase-6"],
    tags: ["Azure", "cloud", "free-tier"],
    free: true,
  },
  {
    id: "lab-fortinet-train",
    title: "Fortinet Training Institute",
    url: "https://training.fortinet.com/",
    type: "lab",
    description: "Free NSE courses and FortiGate virtual lab access.",
    phases: ["phase-4"],
    tags: ["FortiGate", "NSE", "free"],
    free: true,
  },

  // Cert Prep
  {
    id: "cert-boson-exsim",
    title: "Boson ExSim-Max (CCNA)",
    url: "https://www.boson.com/exsim-max",
    type: "cert-prep",
    description: "Realistic CCNA practice exams — use before Gate 1.",
    phases: ["phase-3"],
    tags: ["CCNA", "practice-exam", "exam-prep"],
  },
  {
    id: "cert-pearson-ccna",
    title: "Pearson CCNA Practice Tests",
    url: "https://www.pearsonitcertification.com/store/ccna-200-301-official-cert-guide-premium-edition-9780135792803",
    type: "cert-prep",
    description: "Official Cisco practice questions with explanations.",
    phases: ["phase-3"],
    tags: ["CCNA", "practice-exam"],
  },
  {
    id: "cert-microsoft-learn",
    title: "Microsoft Learn — AZ-700",
    url: "https://learn.microsoft.com/en-us/credentials/certifications/exams/az-700/",
    type: "cert-prep",
    description: "Official AZ-700 study path with sandbox labs.",
    phases: ["phase-5", "phase-6"],
    tags: ["AZ-700", "Azure", "free"],
    free: true,
  },
  {
    id: "cert-fortinet-nse4",
    title: "Fortinet NSE 4 Certification",
    url: "https://www.fortinet.com/training-certification",
    type: "cert-prep",
    description: "NSE 4 exam prep for FortiGate administration.",
    phases: ["phase-4"],
    tags: ["NSE4", "FortiGate", "certification"],
  },
  {
    id: "cert-subnet-practice",
    title: "Subnetting Practice (subnetting.net)",
    url: "https://subnetting.net/",
    type: "cert-prep",
    description: "External subnetting drills — supplement built-in drills.",
    phases: ["phase-1"],
    tags: ["subnetting", "practice", "free"],
    free: true,
  },

  // Tools
  {
    id: "tool-wireshark",
    title: "Wireshark",
    url: "https://www.wireshark.org/download.html",
    type: "tool",
    description: "Protocol analyzer — install on day 1 of Phase 0.",
    phases: ["phase-0"],
    tags: ["packet capture", "analysis", "free"],
    free: true,
  },
  {
    id: "tool-putty",
    title: "PuTTY / Windows Terminal",
    url: "https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html",
    type: "tool",
    description: "SSH client for device management.",
    tags: ["SSH", "CLI", "free"],
    free: true,
  },
  {
    id: "tool-obsidian",
    title: "Obsidian",
    url: "https://obsidian.md/",
    type: "tool",
    description: "Knowledge base for notes, diagrams, and recall cards.",
    tags: ["notes", "knowledge-base", "free"],
    free: true,
  },
  {
    id: "tool-drawio",
    title: "draw.io (diagrams.net)",
    url: "https://app.diagrams.net/",
    type: "tool",
    description: "Network topology and architecture diagrams.",
    tags: ["diagrams", "topology", "free"],
    free: true,
  },
  {
    id: "tool-ansible",
    title: "Ansible",
    url: "https://docs.ansible.com/ansible/latest/getting_started/index.html",
    type: "tool",
    description: "Network automation for Phase 7+ configuration management.",
    phases: ["phase-7"],
    tags: ["automation", "Python", "IaC"],
    free: true,
  },
  {
    id: "tool-python-netmiko",
    title: "Netmiko",
    url: "https://github.com/ktbyers/netmiko",
    type: "tool",
    description: "Python library for multi-vendor SSH automation.",
    phases: ["phase-7"],
    tags: ["Python", "automation", "SSH"],
    free: true,
  },

  // Communities
  {
    id: "community-reddit-ccna",
    title: "r/CCNA",
    url: "https://www.reddit.com/r/CCNA/",
    type: "community",
    description: "Active CCNA study community — ask questions, share labs.",
    phases: ["phase-1", "phase-2", "phase-3"],
    tags: ["CCNA", "community", "free"],
    free: true,
  },
  {
    id: "community-reddit-networking",
    title: "r/networking",
    url: "https://www.reddit.com/r/networking/",
    type: "community",
    description: "Professional networking discussions and career advice.",
    tags: ["career", "professional", "free"],
    free: true,
  },
  {
    id: "community-cisco-learning",
    title: "Cisco Learning Network",
    url: "https://learningnetwork.cisco.com/",
    type: "community",
    description: "Official Cisco community with study groups and forums.",
    tags: ["Cisco", "certification", "free"],
    free: true,
  },
  {
    id: "community-discord-netdev",
    title: "NetworkChuck Academy Discord",
    url: "https://academy.networkchuck.com/",
    type: "community",
    description: "Study accountability groups and peer support.",
    tags: ["accountability", "community"],
    free: true,
  },
  {
    id: "community-techexams",
    title: "TechExams Forum",
    url: "https://community.infosecinstitute.com/categories/certifications",
    type: "community",
    description: "Certification discussion across vendors.",
    tags: ["certification", "forum", "free"],
    free: true,
  },
];

export function getResourcesByType(type: ResourceType): Resource[] {
  return RESOURCES.filter((r) => r.type === type);
}

export function getResourcesByPhase(phaseId: string): Resource[] {
  return RESOURCES.filter((r) => r.phases?.includes(phaseId));
}

export function getFreeResources(): Resource[] {
  return RESOURCES.filter((r) => r.free);
}
