/**
 * Curated single-concept explanation videos for curriculum topics.
 * Primary source: Jeremy's IT Lab CCNA 200-301 (free, CCNA-aligned lectures).
 * Supplement: NetworkChuck for subnetting intuition where noted.
 */

export interface TopicVideo {
  slug: string;
  title: string;
  summary: string;
  youtubeId: string;
  videoTitle: string;
  channel: string;
  channelUrl: string;
  moduleIds: string[];
  phaseIds: string[];
  /** Curriculum topic strings / keywords that resolve to this page */
  aliases: string[];
  /** Optional follow-up videos in the same concept series */
  relatedSlugs?: string[];
  tags?: string[];
}

const JITL = "Jeremy's IT Lab";
const JITL_URL = "https://www.youtube.com/@JeremysITLab";
const NC = "NetworkChuck";
const NC_URL = "https://www.youtube.com/@NetworkChuck";

export const TOPIC_VIDEOS: TopicVideo[] = [
  {
    slug: "osi-model",
    title: "OSI Model",
    summary:
      "What each of the seven OSI layers actually does, how PDUs map to layers, and why the model exists.",
    youtubeId: "t-ai8JzhHuY",
    videoTitle: "OSI Model & TCP/IP Suite — Day 3",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m1-architecture"],
    phaseIds: ["phase-1"],
    aliases: ["osi", "osi model", "osi & tcp/ip models", "pdu terminology"],
    relatedSlugs: ["tcp-ip-model", "encapsulation"],
    tags: ["fundamentals", "layer-1-7"],
  },
  {
    slug: "tcp-ip-model",
    title: "TCP/IP Model",
    summary:
      "The modern TCP/IP stack — physical through application — and how it maps to real protocol behavior.",
    youtubeId: "yM-XNq9ADlI",
    videoTitle: "How the TCP/IP Model Actually Works — Day 3 (2025)",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m1-architecture"],
    phaseIds: ["phase-1"],
    aliases: ["tcp/ip", "tcp ip model", "tcp/ip suite"],
    relatedSlugs: ["osi-model", "encapsulation"],
    tags: ["fundamentals"],
  },
  {
    slug: "encapsulation",
    title: "Encapsulation & Decapsulation",
    summary:
      "How data gets wrapped layer-by-layer on the way out and stripped on the way in — the lifeblood of networking.",
    youtubeId: "t-ai8JzhHuY",
    videoTitle: "OSI Model & TCP/IP Suite (encapsulation section) — Day 3",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m1-architecture"],
    phaseIds: ["phase-1"],
    aliases: ["encapsulation", "decapsulation", "encapsulation/decapsulation"],
    relatedSlugs: ["osi-model", "life-of-a-packet"],
    tags: ["fundamentals"],
  },
  {
    slug: "network-devices",
    title: "Network Devices",
    summary: "Hubs, switches, routers, firewalls — what each device operates on and when you use it.",
    youtubeId: "H8W9oMNSuwo",
    videoTitle: "Network Devices — Day 1",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m0-foundation", "m1-architecture"],
    phaseIds: ["phase-0", "phase-1"],
    aliases: ["network devices", "hubs", "switches", "routers"],
    tags: ["fundamentals"],
  },
  {
    slug: "ethernet-cables",
    title: "Interfaces & Cables",
    summary: "Copper vs fiber, straight-through vs crossover, and the physical layer that everything rides on.",
    youtubeId: "ieTH5lVhNaY",
    videoTitle: "Interfaces and Cables — Day 2",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m2-ethernet"],
    phaseIds: ["phase-1"],
    aliases: ["interfaces", "cables", "copper", "fiber", "duplex/speed"],
    tags: ["ethernet", "layer-1"],
  },
  {
    slug: "lan",
    title: "LAN (Local Area Network)",
    summary:
      "How Ethernet LANs work — collision domains, broadcast domains, and what happens when a frame enters a switch.",
    youtubeId: "u2n762WG0Vo",
    videoTitle: "Ethernet LAN Switching (Part 1) — Day 5",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m2-ethernet", "m1-architecture"],
    phaseIds: ["phase-1"],
    aliases: [
      "lan",
      "local area network",
      "ethernet lan",
      "collision & broadcast domains",
      "collision domain",
      "broadcast domain",
      "broadcast/multicast/unicast",
    ],
    relatedSlugs: ["ethernet-switching", "mac-addresses"],
    tags: ["ethernet", "layer-2"],
  },
  {
    slug: "ethernet-switching",
    title: "Ethernet Switching",
    summary:
      "MAC learning, CAM table, forward/filter/flood — the exact algorithm a switch uses on every frame.",
    youtubeId: "5q1pqdmdPjo",
    videoTitle: "Ethernet LAN Switching (Part 2) — Day 6",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m2-ethernet"],
    phaseIds: ["phase-1"],
    aliases: [
      "ethernet switching",
      "ethernet frame",
      "frame learn",
      "forward/filter/flood",
      "cam table",
    ],
    relatedSlugs: ["lan", "mac-addresses"],
    tags: ["ethernet", "layer-2"],
  },
  {
    slug: "mac-addresses",
    title: "MAC Addresses",
    summary: "48-bit hardware addresses, unicast vs broadcast MACs, and how switches use them.",
    youtubeId: "u2n762WG0Vo",
    videoTitle: "Ethernet LAN Switching (Part 1) — Day 5",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m2-ethernet"],
    phaseIds: ["phase-1"],
    aliases: ["mac", "mac addresses", "mac address", "ethernet frame"],
    relatedSlugs: ["lan", "arp"],
    tags: ["ethernet", "layer-2"],
  },
  {
    slug: "ipv4-addressing",
    title: "IPv4 Addressing",
    summary: "Dotted decimal, classes vs CIDR, public vs private, and how hosts get their IP configuration.",
    youtubeId: "3ROdsfEUuhs",
    videoTitle: "IPv4 Addressing (Part 1) — Day 7",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["ipv4", "ipv4 binary/decimal", "ipv4 addressing", "cidr"],
    relatedSlugs: ["ipv4-addressing-part-2", "subnetting"],
    tags: ["layer-3"],
  },
  {
    slug: "ipv4-addressing-part-2",
    title: "IPv4 Addressing (Advanced)",
    summary: "Special addresses, APIPA, and deeper IPv4 addressing rules you'll see on the exam.",
    youtubeId: "FiAatRd84XI",
    videoTitle: "IPv4 Addressing (Part 2) — Day 8",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["ipv4 part 2", "special ipv4"],
    relatedSlugs: ["ipv4-addressing", "subnetting"],
    tags: ["layer-3"],
  },
  {
    slug: "ipv4-header",
    title: "IPv4 Header",
    summary: "TTL, ToS, flags, fragmentation — field-by-field breakdown of an IPv4 packet header.",
    youtubeId: "aQB22y4liXA",
    videoTitle: "IPv4 Header — Day 10",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting", "m4-tcpip"],
    phaseIds: ["phase-1"],
    aliases: ["ipv4 header", "ip header", "ttl", "tos"],
    tags: ["layer-3"],
  },
  {
    slug: "subnetting",
    title: "Subnetting",
    summary: "Split networks with subnet masks — network address, broadcast, and host range without a calculator.",
    youtubeId: "bQ8sdpGQu8c",
    videoTitle: "Subnetting (Part 1) — Day 13",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["subnetting", "subnet", "flsm", "route summarization"],
    relatedSlugs: ["subnetting-part-2", "vlsm", "subnet-mask"],
    tags: ["layer-3"],
  },
  {
    slug: "subnetting-part-2",
    title: "Subnetting (Part 2)",
    summary: "More subnetting practice patterns and exam-style problems.",
    youtubeId: "IGhd-0di0Qo",
    videoTitle: "Subnetting (Part 2) — Day 14",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["subnetting part 2"],
    relatedSlugs: ["subnetting", "vlsm"],
    tags: ["layer-3"],
  },
  {
    slug: "vlsm",
    title: "VLSM",
    summary: "Variable Length Subnet Masking — assign different mask sizes to subnets based on host needs.",
    youtubeId: "z-JqCedc9EI",
    videoTitle: "Subnetting (Part 3 — VLSM) — Day 15",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["vlsm", "variable length subnet"],
    relatedSlugs: ["subnetting"],
    tags: ["layer-3"],
  },
  {
    slug: "subnet-mask",
    title: "What Is a Subnet Mask?",
    summary: "NetworkChuck's intuitive breakdown of how subnet masks define network vs host portions.",
    youtubeId: "oZGZRtaGyG8",
    videoTitle: "What is a Subnet Mask?",
    channel: NC,
    channelUrl: NC_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["subnet mask"],
    relatedSlugs: ["subnetting"],
    tags: ["layer-3", "supplement"],
  },
  {
    slug: "routing-fundamentals",
    title: "Routing Fundamentals",
    summary: "How routers build routing tables, longest-prefix match, and control plane vs data plane.",
    youtubeId: "aHwAm8GYbn8",
    videoTitle: "Routing Fundamentals — Day 11 (Part 1)",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m7-routing"],
    phaseIds: ["phase-3"],
    aliases: [
      "routing",
      "routing table",
      "routing fundamentals",
      "longest prefix match",
      "control plane vs data plane",
      "recursive lookup",
    ],
    relatedSlugs: ["static-routing", "dynamic-routing"],
    tags: ["layer-3"],
  },
  {
    slug: "static-routing",
    title: "Static Routing",
    summary: "Configure static and default routes — when they make sense and how routers use them.",
    youtubeId: "YCv4-_sMvYE",
    videoTitle: "Static Routing — Day 11 (Part 2)",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m7-routing"],
    phaseIds: ["phase-3"],
    aliases: ["static routing", "static/default routes", "default route", "floating static"],
    relatedSlugs: ["routing-fundamentals", "dynamic-routing"],
    tags: ["layer-3"],
  },
  {
    slug: "dynamic-routing",
    title: "Dynamic Routing",
    summary: "Distance vector vs link state, admin distance, metrics, and how dynamic protocols populate the RIB.",
    youtubeId: "xSTgb8JLkvs",
    videoTitle: "Dynamic Routing — Day 24",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m7-routing", "m9-advanced-routing"],
    phaseIds: ["phase-3"],
    aliases: [
      "dynamic routing",
      "admin distance",
      "metric",
      "distance vector",
      "link-state routing",
    ],
    relatedSlugs: ["ospf-part-1", "routing-fundamentals"],
    tags: ["layer-3"],
  },
  {
    slug: "life-of-a-packet",
    title: "Life of a Packet (ARP & ICMP)",
    summary: "Trace a packet from source to destination — ARP resolution, routing decisions, and ICMP along the way.",
    youtubeId: "4YrYV2io3as",
    videoTitle: "The Life of a Packet — Day 12",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m4-tcpip", "m2-ethernet"],
    phaseIds: ["phase-1"],
    aliases: ["arp", "icmp", "life of a packet", "packet flow"],
    relatedSlugs: ["mac-addresses", "routing-fundamentals"],
    tags: ["layer-2", "layer-3"],
  },
  {
    slug: "tcp-udp",
    title: "TCP & UDP",
    summary: "Transport layer protocols — three-way handshake, ports, reliability vs speed.",
    youtubeId: "LIEACBqlntY",
    videoTitle: "TCP & UDP — Day 30",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m4-tcpip"],
    phaseIds: ["phase-1"],
    aliases: [
      "tcp",
      "udp",
      "tcp/udp",
      "tcp, udp",
      "three-way handshake",
      "three-way handshake, flags, windows",
    ],
    relatedSlugs: ["life-of-a-packet"],
    tags: ["layer-4"],
  },
  {
    slug: "vlan",
    title: "VLANs",
    summary: "Virtual LANs — broadcast domain segmentation, access ports, and why VLANs exist.",
    youtubeId: "cjFzOnm6u1g",
    videoTitle: "VLANs (Part 1) — Day 16",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m5-vlan"],
    phaseIds: ["phase-2"],
    aliases: ["vlan", "vlans", "access/trunk ports", "broadcast domain"],
    relatedSlugs: ["trunk-8021q", "inter-vlan-routing"],
    tags: ["layer-2"],
  },
  {
    slug: "trunk-8021q",
    title: "Trunks & 802.1Q",
    summary: "Carry multiple VLANs on one link — 802.1Q tagging, native VLAN, and trunk negotiation.",
    youtubeId: "Jl9OOzNaBDU",
    videoTitle: "VLANs (Part 2) — Day 17",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m5-vlan"],
    phaseIds: ["phase-2"],
    aliases: ["trunk", "802.1q", "native vlan", "router-on-a-stick"],
    relatedSlugs: ["vlan", "inter-vlan-routing"],
    tags: ["layer-2"],
  },
  {
    slug: "inter-vlan-routing",
    title: "Inter-VLAN Routing & SVIs",
    summary: "Route between VLANs with SVIs on a Layer-3 switch or router-on-a-stick.",
    youtubeId: "OkPB028l2eE",
    videoTitle: "VLANs (Part 3) — Day 18",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m5-vlan"],
    phaseIds: ["phase-2"],
    aliases: ["inter-vlan routing", "svi", "svis", "layer 3 switch"],
    relatedSlugs: ["vlan", "trunk-8021q"],
    tags: ["layer-2", "layer-3"],
  },
  {
    slug: "stp",
    title: "Spanning Tree Protocol (STP)",
    summary: "Prevent Layer-2 loops — root bridge election, port roles, and BPDU exchange.",
    youtubeId: "j-bK-EFt9cY",
    videoTitle: "Spanning Tree Protocol (Part 1) — Day 20",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m6-stp"],
    phaseIds: ["phase-2"],
    aliases: ["stp", "spanning tree", "root bridge", "bpdu", "portfast", "bpdu guard"],
    relatedSlugs: ["stp-part-2", "rstp"],
    tags: ["layer-2"],
  },
  {
    slug: "stp-part-2",
    title: "STP (Part 2)",
    summary: "STP port states, timers, and convergence — plus PortFast and BPDU Guard in context.",
    youtubeId: "nWpldCc8msY",
    videoTitle: "Spanning Tree Protocol (Part 2) — Day 21",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m6-stp"],
    phaseIds: ["phase-2"],
    aliases: ["stp part 2", "root guard", "loop guard"],
    relatedSlugs: ["stp", "rstp"],
    tags: ["layer-2"],
  },
  {
    slug: "rstp",
    title: "Rapid STP (RSTP)",
    summary: "Faster convergence with RSTP — alternate/backup ports and proposal/agreement.",
    youtubeId: "EpazNsLlPps",
    videoTitle: "Rapid Spanning Tree Protocol — Day 22",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m6-stp"],
    phaseIds: ["phase-2"],
    aliases: ["rstp", "rapid stp", "stp/rstp"],
    relatedSlugs: ["stp"],
    tags: ["layer-2"],
  },
  {
    slug: "etherchannel",
    title: "EtherChannel & LACP",
    summary: "Bundle links for bandwidth and redundancy — PAgP, LACP, and load-balancing.",
    youtubeId: "xuo69Joy_Nc",
    videoTitle: "EtherChannel — Day 23",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m6-stp"],
    phaseIds: ["phase-2"],
    aliases: ["etherchannel", "lacp", "port channel"],
    relatedSlugs: ["stp"],
    tags: ["layer-2"],
  },
  {
    slug: "ospf-part-1",
    title: "OSPF (Part 1)",
    summary: "Link-state basics, OSPF neighbors, Hello packets, and getting adjacencies up.",
    youtubeId: "pvuaoJ9YzoI",
    videoTitle: "OSPF Part 1 — Day 26",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m8-ospf"],
    phaseIds: ["phase-3"],
    aliases: ["ospf", "link-state routing", "ospf neighbors"],
    relatedSlugs: ["ospf-part-2", "ospf-part-3"],
    tags: ["layer-3", "routing-protocol"],
  },
  {
    slug: "ospf-part-2",
    title: "OSPF (Part 2)",
    summary: "LSAs, LSDB, SPF algorithm, and how OSPF builds its routing table.",
    youtubeId: "VtzfTA21ht0",
    videoTitle: "OSPF Part 2 — Day 27",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m8-ospf"],
    phaseIds: ["phase-3"],
    aliases: ["lsas", "lsdb", "spf"],
    relatedSlugs: ["ospf-part-1", "ospf-part-3"],
    tags: ["layer-3", "routing-protocol"],
  },
  {
    slug: "ospf-part-3",
    title: "OSPF (Part 3)",
    summary: "Areas, DR/BDR, network types, authentication, and route summarization.",
    youtubeId: "3ew26ujkiDI",
    videoTitle: "OSPF Part 3 — Day 28",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m8-ospf"],
    phaseIds: ["phase-3"],
    aliases: ["ospf areas", "dr/bdr", "network types"],
    relatedSlugs: ["ospf-part-1", "ospf-part-2"],
    tags: ["layer-3", "routing-protocol"],
  },
  {
    slug: "fhrrp",
    title: "First Hop Redundancy (HSRP/VRRP)",
    summary: "Default gateway redundancy with HSRP, VRRP, and GLBP.",
    youtubeId: "43WnpwQMolo",
    videoTitle: "First Hop Redundancy Protocols — Day 29",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m17-enterprise"],
    phaseIds: ["phase-6"],
    aliases: ["hsrp", "vrrp", "first hop redundancy", "redundancy"],
    tags: ["layer-3"],
  },
  {
    slug: "ipv6",
    title: "IPv6 (Part 1)",
    summary: "IPv6 addressing, notation, and how it compares to IPv4.",
    youtubeId: "ZNuXyOXae5U",
    videoTitle: "IPv6 Part 1 — Day 31",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["ipv6", "ipv6 structure", "slaac", "ndp", "dhcpv6"],
    relatedSlugs: ["ipv6-part-2", "ipv6-part-3"],
    tags: ["layer-3"],
  },
  {
    slug: "ipv6-part-2",
    title: "IPv6 (Part 2)",
    summary: "IPv6 configuration, EUI-64, and static addressing.",
    youtubeId: "BrTMMOXFhDU",
    videoTitle: "IPv6 Part 2 — Day 32",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["ipv6 part 2", "eui-64"],
    relatedSlugs: ["ipv6", "ipv6-part-3"],
    tags: ["layer-3"],
  },
  {
    slug: "ipv6-part-3",
    title: "IPv6 (Part 3)",
    summary: "IPv6 routing, OSPFv3, and transition mechanisms.",
    youtubeId: "rwkHfsWQwy8",
    videoTitle: "IPv6 Part 3 — Day 33",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m3-subnetting"],
    phaseIds: ["phase-1"],
    aliases: ["ipv6 part 3", "ospfv3"],
    relatedSlugs: ["ipv6", "ipv6-part-2"],
    tags: ["layer-3"],
  },
  {
    slug: "standard-acls",
    title: "Standard ACLs",
    summary: "Filter traffic by source IP — where to place standard ACLs and wildcard masks.",
    youtubeId: "z023_eRUtSo",
    videoTitle: "Standard ACLs — Day 34",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m14-network-security"],
    phaseIds: ["phase-5"],
    aliases: ["standard acl", "standard acls", "acls"],
    relatedSlugs: ["extended-acls"],
    tags: ["security"],
  },
  {
    slug: "extended-acls",
    title: "Extended ACLs",
    summary: "Filter by source, destination, protocol, and port — granular traffic control.",
    youtubeId: "dUttKY_CNXE",
    videoTitle: "Extended ACLs — Day 35",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m14-network-security"],
    phaseIds: ["phase-5"],
    aliases: ["extended acl", "extended acls", "route filtering"],
    relatedSlugs: ["standard-acls"],
    tags: ["security"],
  },
  {
    slug: "dns",
    title: "DNS",
    summary: "How domain names resolve to IP addresses — records, hierarchy, and troubleshooting.",
    youtubeId: "4C6eeQes4cs",
    videoTitle: "DNS — Day 38",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m4-tcpip", "m10-services"],
    phaseIds: ["phase-1", "phase-4"],
    aliases: ["dns"],
    relatedSlugs: ["dhcp"],
    tags: ["services"],
  },
  {
    slug: "dhcp",
    title: "DHCP",
    summary: "Dynamic Host Configuration Protocol — DORA process, scopes, and relay agents.",
    youtubeId: "hzkleGAC2_Y",
    videoTitle: "DHCP — Day 39",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m4-tcpip", "m10-services"],
    phaseIds: ["phase-1", "phase-4"],
    aliases: ["dhcp"],
    relatedSlugs: ["dns"],
    tags: ["services"],
  },
  {
    slug: "ntp",
    title: "NTP",
    summary: "Network Time Protocol — why synchronized clocks matter for logs and security.",
    youtubeId: "qGJaJx7OfUo",
    videoTitle: "NTP — Day 37",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m10-services"],
    phaseIds: ["phase-4"],
    aliases: ["ntp"],
    tags: ["services"],
  },
  {
    slug: "snmp",
    title: "SNMP",
    summary: "Simple Network Management Protocol — polling, traps, and MIBs for monitoring.",
    youtubeId: "HXu0Ifj0oWU",
    videoTitle: "SNMP — Day 40",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m10-services", "m18-monitoring"],
    phaseIds: ["phase-4", "phase-6"],
    aliases: ["snmp", "snmp, netflow, telemetry"],
    tags: ["services", "monitoring"],
  },
  {
    slug: "syslog",
    title: "Syslog",
    summary: "Centralized logging — severity levels, facilities, and sending logs to a collector.",
    youtubeId: "RaQPSKQ4J5A",
    videoTitle: "Syslog — Day 41",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m10-services", "m18-monitoring"],
    phaseIds: ["phase-4", "phase-6"],
    aliases: ["syslog"],
    tags: ["services", "monitoring"],
  },
  {
    slug: "ssh",
    title: "SSH",
    summary: "Secure remote access — key exchange, encryption, and replacing Telnet.",
    youtubeId: "AvgYqI2qSD4",
    videoTitle: "SSH — Day 42",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m0-foundation", "m4-tcpip"],
    phaseIds: ["phase-0", "phase-1"],
    aliases: ["ssh", "ssh & virtual machines"],
    relatedSlugs: ["linux-fundamentals"],
    tags: ["services", "security"],
  },
  {
    slug: "nat",
    title: "NAT (Part 1)",
    summary: "Network Address Translation — inside/outside, static NAT, and why NAT exists.",
    youtubeId: "2TZCfTgopeg",
    videoTitle: "NAT (Part 1) — Day 44",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m11-wan"],
    phaseIds: ["phase-4"],
    aliases: ["nat", "nat/pat", "static nat"],
    relatedSlugs: ["nat-part-2"],
    tags: ["wan"],
  },
  {
    slug: "nat-part-2",
    title: "NAT (Part 2 — PAT)",
    summary: "Port Address Translation (PAT/overload) — how many hosts share one public IP.",
    youtubeId: "kILDNs4KjYE",
    videoTitle: "NAT (Part 2) — Day 45",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m11-wan"],
    phaseIds: ["phase-4"],
    aliases: ["pat", "port address translation", "dynamic nat"],
    relatedSlugs: ["nat"],
    tags: ["wan"],
  },
  {
    slug: "qos",
    title: "QoS (Part 1)",
    summary: "Quality of Service fundamentals — classification, marking, and why queuing matters.",
    youtubeId: "H6FKJMiiL6E",
    videoTitle: "QoS (Part 1) — Day 46",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m12-wireless-qos"],
    phaseIds: ["phase-4"],
    aliases: ["qos", "classification, marking, queuing, shaping"],
    relatedSlugs: ["qos-part-2"],
    tags: ["qos"],
  },
  {
    slug: "qos-part-2",
    title: "QoS (Part 2)",
    summary: "Queuing, shaping, and policing — implementing QoS policies on Cisco gear.",
    youtubeId: "4vurfhVjcMM",
    videoTitle: "QoS (Part 2) — Day 47",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m12-wireless-qos"],
    phaseIds: ["phase-4"],
    aliases: ["queuing", "shaping", "policing"],
    relatedSlugs: ["qos"],
    tags: ["qos"],
  },
  {
    slug: "security-fundamentals",
    title: "Security Fundamentals",
    summary: "CIA triad, common threats, defense in depth, and security best practices for networks.",
    youtubeId: "VvFuieyTTSw",
    videoTitle: "Security Fundamentals — Day 48",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m13-security-fundamentals"],
    phaseIds: ["phase-5"],
    aliases: ["threats & vulnerabilities", "security fundamentals", "cia"],
    tags: ["security"],
  },
  {
    slug: "port-security",
    title: "Port Security",
    summary: "Restrict MAC addresses on switch ports — sticky MAC, violation modes, and recovery.",
    youtubeId: "sHN3jOJIido",
    videoTitle: "Port Security — Day 49",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m14-network-security"],
    phaseIds: ["phase-5"],
    aliases: ["port security", "l2 security features"],
    tags: ["security", "layer-2"],
  },
  {
    slug: "wireless-fundamentals",
    title: "Wireless Fundamentals (802.11 & RF)",
    summary:
      "Wi-Fi standards, radio frequency bands, channels, and service sets — the foundation before configuring WLANs.",
    youtubeId: "zuYiktLqNYQ",
    videoTitle: "Wireless Fundamentals — Day 55",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m12-wireless-qos"],
    phaseIds: ["phase-4"],
    aliases: [
      "wireless",
      "802.11",
      "802.11, rf, wlan auth",
      "wifi",
      "wi-fi",
      "wireless fundamentals",
      "rf",
      "ssid",
    ],
    relatedSlugs: ["wireless-architectures"],
    tags: ["wireless", "layer-1"],
  },
  {
    slug: "wireless-architectures",
    title: "Wireless Architectures",
    summary:
      "802.11 frame format, autonomous vs lightweight APs, WLC deployment models, and AP operational modes.",
    youtubeId: "uX1h0F6wpBY",
    videoTitle: "Wireless Architectures — Day 56",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m12-wireless-qos"],
    phaseIds: ["phase-4"],
    aliases: [
      "wireless architectures",
      "wlan",
      "wlc",
      "lightweight ap",
      "autonomous ap",
    ],
    relatedSlugs: ["wireless-fundamentals", "qos"],
    tags: ["wireless"],
  },
  {
    slug: "cdp-lldp",
    title: "CDP & LLDP",
    summary:
      "Layer 2 discovery protocols — Cisco CDP vs industry-standard LLDP, configuration, and show commands.",
    youtubeId: "_hnMZBzXRRk",
    videoTitle: "CDP & LLDP — Day 36",
    channel: JITL,
    channelUrl: JITL_URL,
    moduleIds: ["m10-services"],
    phaseIds: ["phase-4"],
    aliases: ["cdp", "lldp", "cdp/lldp", "layer 2 discovery", "discovery protocols"],
    relatedSlugs: ["snmp", "syslog"],
    tags: ["services", "layer-2"],
  },
  {
    slug: "linux-fundamentals",
    title: "Linux Fundamentals",
    summary:
      "Shells, terminals, and Unix-like basics — navigate files, install packages, and get comfortable on the command line before CCNA labs.",
    youtubeId: "v392lEyM29A",
    videoTitle: "Learn Linux — The Full Course",
    channel: "Boot.dev",
    channelUrl: "https://www.youtube.com/@bootdotdev",
    moduleIds: ["m0-foundation"],
    phaseIds: ["phase-0"],
    aliases: [
      "linux fundamentals",
      "linux",
      "cli navigation",
      "basic bash, powershell, python",
    ],
    tags: ["linux", "fundamentals"],
  },
];

/** Topics intentionally deferred until curated single-concept sources are verified */
export const TOPIC_VIDEO_DEFERRALS = [
  { area: "Azure (AZ-104 / AZ-700)", reason: "Use John Savill / Microsoft Learn playlists — not yet mapped to single-concept pages" },
  { area: "Fortinet NSE 4", reason: "Vendor-specific; FortiGate lab content planned separately from CCNA Jeremy lectures" },
  { area: "BGP / advanced routing", reason: "Beyond CCNA simulator scope; external EVE-NG labs recommended" },
  { area: "Automation / SDN / Python", reason: "Hands-on code labs; video embeds TBD per module" },
  { area: "Wireless Security (Day 57)", reason: "YouTube ID not verified for lecture-only video" },
] as const;

const slugIndex = new Map(TOPIC_VIDEOS.map((t) => [t.slug, t]));

/** Normalize curriculum topic label for matching */
function normalizeLabel(label: string): string {
  return label
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^\w\s/+-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Score how well an alias matches a curriculum label (higher = better) */
function aliasScore(alias: string, label: string): number {
  const a = normalizeLabel(alias);
  const l = normalizeLabel(label);
  if (!a || !l) return 0;
  if (a === l) return 100;
  if (l.includes(a)) return 80 + a.length;
  if (a.includes(l)) return 60 + l.length;
  const aWords = a.split(" ");
  const lWords = l.split(" ");
  const overlap = aWords.filter((w) => w.length > 2 && lWords.some((lw) => lw.includes(w) || w.includes(lw)));
  return overlap.length * 15;
}

export function getTopicBySlug(slug: string): TopicVideo | undefined {
  return slugIndex.get(slug);
}

export function getAllTopics(): TopicVideo[] {
  return TOPIC_VIDEOS;
}

export function getRelatedTopics(slugs: string[] | undefined): TopicVideo[] {
  if (!slugs?.length) return [];
  return slugs.map((s) => slugIndex.get(s)).filter((t): t is TopicVideo => Boolean(t));
}

export function getTopicsForModule(moduleId: string): TopicVideo[] {
  return TOPIC_VIDEOS.filter((t) => t.moduleIds.includes(moduleId));
}

export function getTopicsForPhase(phaseId: string): TopicVideo[] {
  return TOPIC_VIDEOS.filter((t) => t.phaseIds.includes(phaseId));
}

/** Resolve a curriculum topic string to a topic page slug, if one exists */
export function resolveTopicSlug(label: string): string | undefined {
  let best: { slug: string; score: number } | undefined;

  for (const topic of TOPIC_VIDEOS) {
    for (const alias of topic.aliases) {
      const score = aliasScore(alias, label);
      if (score >= 45 && (!best || score > best.score)) {
        best = { slug: topic.slug, score };
      }
    }
  }

  return best?.slug;
}

export function hasTopicVideo(label: string): boolean {
  return resolveTopicSlug(label) !== undefined;
}
